# Run as Administrator: powershell -ExecutionPolicy Bypass -File fix_path.ps1
# Restores system PATH that was truncated by setx's 1024-char limit.

$restored = @(
    'E:\AI\venv\Scripts'
    'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\bin'
    'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\libnvvp'
    'C:\Program Files\Eclipse Adoptium\jre-21.0.4.7-hotspot\bin'
    'C:\Program Files\Eclipse Adoptium\jre-8.0.422.5-hotspot\bin'
    'C:\Program Files\Eclipse Adoptium\jre-17.0.12.7-hotspot\bin'
    'C:\Program Files\Eclipse Adoptium\jre-11.0.24.8-hotspot\bin'
    'C:\Program Files (x86)\Eclipse Adoptium\jre-8.0.422.5-hotspot\bin'
    'C:\WINDOWS\system32'
    'C:\WINDOWS'
    'C:\WINDOWS\System32\Wbem'
    'C:\WINDOWS\System32\WindowsPowerShell\v1.0\'
    'C:\WINDOWS\System32\OpenSSH\'
    'C:\Program Files\Microsoft VS Code\bin'
    'C:\Program Files\dotnet\'
    'C:\Program Files\NVIDIA Corporation\Nsight Compute 2024.3.2\'
    'C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common'
    'C:\Program Files\Git\cmd'
    'C:\Users\calla\AppData\Local\Programs\Python\Python310\Scripts\'
    'C:\Users\calla\AppData\Loc'
    'C:\Program Files\CMake\bin'
    'C:\Program Files\nodejs'
    'C:\Program Files\Docker\Docker\resources\bin'
    'C:\Program Files\TortoiseSVN\bin'
    'C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.43.34808\bin\Hostx86\x64'
    'C:\Users\calla\AppData\Local\Programs\Python\Python312\Scripts'
    'C:\Program Files\MariaDB 11.7\bin'
    'C:\Users\calla\Downloads\ffmpeg-master-latest-win64-gpl\ffmpeg-master-latest-win64-gpl\bin'
    'C:\Program Files\GitHub CLI'
    'C:\Program Files\NVIDIA Corporation\NVIDIA App\NvDLISR'
    'C:\Program Files\Microsoft SQL Server\150\Tools\Binn'
    'C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn'
    'C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit'
    'C:\ProgramData\chocolatey\bin'
    'C:\Program Files\Memurai'
    'C:\Program Files\7-Zip'
    'C:\Users\calla\Downloads\exiftool-13.39_64\exiftool-13.39_64'
    'J:\Archives\UnRAR.exe'
    'C:\Program Files\Mullvad VPN\resources'
    'C:\Users\calla\Downloads\yt-dlp'
) -join ';'

Write-Host "Restoring system PATH ($($restored.Length) chars)..."
[Environment]::SetEnvironmentVariable('Path', $restored, 'Machine')
Write-Host "Done. System PATH restored."
