"""Tests for the dropdown-source generator.

Ensures the TS artifact emitted by `web.scripts.generate_types.generate_dropdown_sources_ts`
reflects the CTk `options_kv` calls in `modules/ui/{ConvertModelUI,ConceptWindow}.py`
and the `TOOL_DROPDOWN_OPTIONS` table in `web/scripts/ui_metadata.py`. A regression
here would re-introduce drift between the web UI dropdowns and their Python source.
"""

from __future__ import annotations

import pytest

generate_types = pytest.importorskip(
    "web.scripts.generate_types",
    reason="generator must be importable",
)


@pytest.fixture(scope="module")
def generated_ts() -> str:
    return generate_types.generate_dropdown_sources_ts()


def test_output_includes_standard_ts_header(generated_ts: str) -> None:
    assert generated_ts.startswith("// Auto-generated by web/scripts/generate_types.py")
    assert "export interface DropdownOption" in generated_ts


def test_convert_model_types_include_all_ctk_entries(generated_ts: str) -> None:
    """AST-parsed Convert modal options_kv should round-trip through the generator.

    Uses `FLUX_2` + `Z_IMAGE` as canaries — these are newer entries that the
    previous hardcoded frontend list was missing, so their presence proves the
    AST parser is sourcing from the live CTk file.
    """
    assert "CONVERT_MODEL_TYPES" in generated_ts
    assert '{ label: "Flux 2", value: "FLUX_2" }' in generated_ts
    assert '{ label: "ZImage", value: "Z_IMAGE" }' in generated_ts


def test_convert_training_methods_resolve_enum_values(generated_ts: str) -> None:
    """`TrainingMethod.FINE_TUNE` attribute refs must resolve to the enum .value."""
    assert "CONVERT_TRAINING_METHODS" in generated_ts
    assert '{ label: "Base Model", value: "FINE_TUNE" }' in generated_ts
    assert '{ label: "LoRA", value: "LORA" }' in generated_ts


def test_concept_prompt_sources_from_ctk(generated_ts: str) -> None:
    assert "PROMPT_SOURCES" in generated_ts
    assert '{ label: "From text file per sample", value: "sample" }' in generated_ts
    assert '{ label: "From image file name", value: "filename" }' in generated_ts


def test_tag_dropout_modes_preserve_space_in_value(generated_ts: str) -> None:
    """`RANDOM WEIGHTED` is a space-separated string literal in CTk; preserving it
    verbatim matters because ConceptTextConfig persists this exact token."""
    assert '{ label: "Random Weighted", value: "RANDOM WEIGHTED" }' in generated_ts


def test_tool_dropdown_options_emitted(generated_ts: str) -> None:
    for name in ("CAPTION_MODELS", "CAPTION_MODES", "MASK_MODELS", "MASK_MODES"):
        assert f"export const {name}: DropdownOption[]" in generated_ts, f"missing {name}"
    # Web-specific tool additions beyond the CTk source:
    assert '{ label: "OpenAI Compatible", value: "OpenAI Compatible" }' in generated_ts
    assert '{ label: "YOLO", value: "YOLO" }' in generated_ts
    # Backend-internal mode keys round-tripped through the metadata table:
    assert '{ label: "Replace all masks", value: "replace" }' in generated_ts
    assert '{ label: "Blend with existing", value: "blend" }' in generated_ts
