"""Tests for the loss-weight type generator.

Ensures the TS artifact emitted by
`web.scripts.generate_types.generate_loss_weight_info_ts` stays aligned with
`LossWeight.supports_flow_matching()`. The web UI's loss_weight_fn dropdown
filters on this map; if it desyncs, flow-matching users can silently pick
values that train incorrectly.
"""

from __future__ import annotations

import pytest

generate_types = pytest.importorskip(
    "web.scripts.generate_types",
    reason="generator must be importable",
)

from modules.util.enum.LossWeight import LossWeight  # noqa: E402


@pytest.fixture(scope="module")
def generated_ts() -> str:
    ts = generate_types.generate_loss_weight_info_ts()
    if "LOSS_WEIGHT_SUPPORTS_FLOW_MATCHING: Record<LossWeight, boolean>" not in ts:
        pytest.fail("generator output missing expected export header")
    return ts


def test_output_includes_standard_ts_header(generated_ts: str) -> None:
    assert generated_ts.startswith("// Auto-generated by web/scripts/generate_types.py")
    assert "import type { LossWeight } from './enums';" in generated_ts


def test_every_loss_weight_value_is_emitted(generated_ts: str) -> None:
    for member in LossWeight:
        assert f'"{member.value}":' in generated_ts, f"LossWeight member {member.value} missing from generator output"


def test_constant_is_present(generated_ts: str) -> None:
    assert '"CONSTANT":' in generated_ts


def test_has_both_true_and_false_members(generated_ts: str) -> None:
    true_count = sum(1 for m in LossWeight if m.supports_flow_matching())
    false_count = sum(1 for m in LossWeight if not m.supports_flow_matching())
    assert true_count >= 1, "expected at least one LossWeight with supports_flow_matching() True"
    assert false_count >= 1, "expected at least one LossWeight with supports_flow_matching() False"
    # Output should contain both literal boolean values.
    assert ": true," in generated_ts
    assert ": false," in generated_ts


def test_constant_marked_true(generated_ts: str) -> None:
    """CONSTANT is always allowed (it's the neutral fallback)."""
    assert '"CONSTANT": true,' in generated_ts
