"""Tests for the layer-preset type generator.

Ensures the TS artifact emitted by `web.scripts.generate_types.generate_layer_presets_ts`
stays aligned with `Base*Setup.LAYER_PRESETS`. If these break, the web UI dropdown
will desync from the CTk dropdown and training can fail with
`ValueError('Custom layer filters: no modules were matched')`.
"""

from __future__ import annotations

import pytest

generate_types = pytest.importorskip(
    "web.scripts.generate_types",
    reason="generator must be importable",
)


@pytest.fixture(scope="module")
def generated_ts() -> str:
    ts = generate_types.generate_layer_presets_ts()
    if "LAYER_PRESETS_BY_MODEL: Partial<Record<ModelType, LayerPresetMap>> = {" not in ts:
        pytest.fail("generator output missing expected export header")
    return ts


def test_output_includes_standard_ts_header(generated_ts: str) -> None:
    assert generated_ts.startswith("// Auto-generated by web/scripts/generate_types.py")
    assert "import type { ModelType } from './enums';" in generated_ts
    assert "export interface LayerPresetDef" in generated_ts
    assert "export const EMPTY_PRESETS" in generated_ts


def test_z_image_preserves_regex_form(generated_ts: str) -> None:
    """BaseZImageSetup uses the dict form {'patterns': [...], 'regex': True}.

    The generator must normalize it without losing the regex flag or the
    refiner-excluding lookahead patterns — those are required for training to
    match any modules.
    """
    assert '"Z_IMAGE": {' in generated_ts
    # Pattern strings are preserved verbatim inside the Z_IMAGE block.
    assert '"^(?=.*attention)(?!.*refiner).*"' in generated_ts
    assert '"^(?=.*feed_forward)(?!.*refiner).*"' in generated_ts
    # attn-mlp and attn-only must be marked regex: true
    z_block = generated_ts.split('"Z_IMAGE": {', 1)[1].split("\n  },", 1)[0]
    attn_mlp_line = (
        '"attn-mlp": { patterns: ["^(?=.*attention)(?!.*refiner).*", '
        '"^(?=.*feed_forward)(?!.*refiner).*"], regex: true }'
    )
    assert attn_mlp_line in z_block
    assert '"attn-only": { patterns: ["^(?=.*attention)(?!.*refiner).*"], regex: true }' in z_block


def test_all_registered_lora_model_families_emitted(generated_ts: str) -> None:
    # ModelType.value strings that have a Base*Setup with LAYER_PRESETS.
    required = [
        "STABLE_DIFFUSION_15",
        "STABLE_DIFFUSION_XL_10_BASE",
        "STABLE_DIFFUSION_3",
        "FLUX_DEV_1",
        "FLUX_2",
        "CHROMA_1",
        "QWEN",
        "SANA",
        "HUNYUAN_VIDEO",
        "HI_DREAM_FULL",
        "PIXART_ALPHA",
        "PIXART_SIGMA",
        "WUERSTCHEN_2",
        "Z_IMAGE",
    ]
    for mt in required:
        assert f'"{mt}": {{' in generated_ts, f"missing preset block for {mt}"


def test_list_form_presets_default_to_regex_false(generated_ts: str) -> None:
    """SD 1.5 / SDXL etc. use list form — must be emitted with regex: false."""
    sd15_block = generated_ts.split('"STABLE_DIFFUSION_15": {', 1)[1].split("\n  },", 1)[0]
    assert '"attn-mlp": { patterns: ["attentions"], regex: false }' in sd15_block
    assert '"attn-only": { patterns: ["attn"], regex: false }' in sd15_block
    assert '"full": { patterns: [], regex: false }' in sd15_block


def test_full_preset_present_for_every_emitted_family(generated_ts: str) -> None:
    """Every Base*Setup defines a 'full' entry — it must survive generation."""
    import re

    body = generated_ts.split("LAYER_PRESETS_BY_MODEL", 1)[1]
    # Top-level ModelType entries are indented with exactly 2 spaces.
    top_level_headers = re.findall(r"^  \"([A-Z0-9_]+)\": \{$", body, flags=re.MULTILINE)
    assert top_level_headers, "no ModelType blocks found in generator output"

    for mt_name in top_level_headers:
        block_start = body.index(f'  "{mt_name}": {{')
        block_end = body.index("\n  },", block_start)
        block = body[block_start:block_end]
        assert '"full":' in block, f"missing 'full' preset in block for {mt_name}"
